name: db-connect
on:
  workflow_dispatch:
  push:
    branches:
    - master
env:
  MONGODB_CLUSTER_ADDRESS: will-be-overridden            # overridden
  MONGODB_USERNAME: ${{secrets.DB_USER}}                 # from regular secret
  MONGODB_DB_NAME: cluster0                              # from here
jobs:
  test:
    runs-on: ubuntu-latest
    environment: development
    env:
      MONGODB_CLUSTER_ADDRESS: ${{env.DB_ADDRESS}}       # from environment
      PORT: ${{env.DB_PORT}}                             # from environment
      MONGODB_PASSWORD: ${{secrets.DB_PASSWORD}}         # from environment
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: cache-dep
      uses: actions/cache@v4
      with:
        key: dependencies-${{hashFiles('**/package-lock.json')}}
        path: node_modules
    - name: install dependencies
      if: steps.cache-dep.hit != 'true'
      run: npm ci
    - name: Run server
      run: npm start & npx wait-on http://127.0.0.1:${{env.PORT}}
