name: db-connect
on:
  workflow_dispatch:
  push:
    branches:
    - master
env:
  MONGODB_CLUSTER_ADDRESS: cluster0.bysk2f.mongodb.net
  MONGODB_USERNAME: sami
  MONGODB_PASSWORD: n84IwLbV2SW9q35N
  MONGODB_DB_NAME: cluster0
  PORT: 27017
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.bysk2fi.mongodb.net
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: cache-dep
      uses: actions/cache@v4
      with:
        key: dependencies-${{hashFiles('**/package-lock.json')}}
        path: node_modules
    - name: install dependencies
      if: steps.cache-dep.hit != 'true'
      run: npm ci
    - name: Run server
      run: npm start & npx wait-on http://127.0.0.1:${{env.PORT}}
